config/routes.rb
Rails.application.routes.draw do
  resources :scholarships

  resources :majors

  resources :schools

  resources :stories

  resources :pins

  devise_for :users
  root "pins#index"

  get "about" => "pages#about" # creates about_path
  get "scholarships" => "pages#scholarships" # creates scholarships_path

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
	belongs_to :major
	belongs_to :school
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]

  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
  end

  # GET /scholarships/new
  def new
    @scholarship = Scholarship.new
    @schools = School.all
    @majors = Major.all
  end

  # GET /scholarships/1/edit
  def edit
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(scholarship_params)

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship }
      else
        format.html { render :new }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarships/1
  # PATCH/PUT /scholarships/1.json
  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship }
      else
        format.html { render :edit }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to scholarships_url, notice: 'Scholarship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_params
      params.require(:scholarship).permit(:school_id, :major_id, :name)
    end
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_form.html.erb
<%= form_for(:scholarship) do |f| %>
  <% if @scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scholarship.errors.count, "error") %> prohibited this scholarship from being saved:</h2>

      <ul>
      <% @scholarship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %><br>
    <%= f.collection_select :school_id, @schools.sort_by(&:name), :id, :name %>
  </div>
  <div class="field">
    <%= f.label :major_id %><br>
    <%= f.collection_select :major_id, @majors.sort_by(&:name), :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scholarships/edit.html.erb
<h1>Editing scholarship</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholarship %> |
<%= link_to 'Back', scholarships_path %>

app/views/scholarships/index.html.erb
<div class="panel panel-info">
 <div class="panel-heading"><h1>Listing scholarships</h1></div>
  <div class="panel-body">
    <table>
  <thead>
    <tr>
      <th>School</th>
      
      <th>Major</th>
      <th></th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scholarships.each do |scholarship| %>
      <tr>
        <td><%= scholarship.school.name %></td>
         
        <td><%= scholarship.major.name %></td>
        <th></th>
        <td><%= scholarship.name %></td>
        <th></th>

        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scholarship', new_scholarship_path %>

  </div>
</div>

app/views/scholarships/new.html.erb
<h1>New scholarship</h1>

<%= render 'form' %>

<%= link_to 'Back', scholarships_path %>

app/views/scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @scholarship.school.name %>
  <th></th>
</p>

<p>
  <strong>Major:</strong>
  <%= @scholarship.major.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @scholarship.name %>
</p>

<%= link_to 'Edit', edit_scholarship_path(@scholarship) %> |
<%= link_to 'Back', scholarships_path %>